from pathlib import Path

TOPIC = "Movies & Entertainment"
ASSIGNED_SITE = "IMDb"

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DOWNLOAD_DIR = BASE_DIR / "downloads"
SOURCE_DB = DATA_DIR / "imdb_source.db"
OUTPUT_DB = DATA_DIR / "imdb.db"
TEST_OUTPUT_DB = DATA_DIR / "imdb_test.db"

# Local mirror. The crawler performs REAL HTTP requests against this host.
MIRROR_HOST = "127.0.0.1"
MIRROR_PORT = 8765
MIRROR_PAGE_SIZE = 1000

# Crawl configuration. The mirror topology is root(depth 0) -> listing(depth 1)
# -> movie detail(depth 2), so MAX_DEPTH=2 is enough to reach every movie.
MAX_DEPTH = 2
REQUEST_TIMEOUT = 90
CRAWL_DELAY = 0.0  # localhost only; do NOT reuse this value for external websites
WORKERS = 8
FETCH_BATCH_SIZE = 256
USER_AGENT = "SEG301-IMDb-LocalMirrorCrawler/1.1 (academic assignment)"
REQUEST_RETRIES = 4
RETRY_BACKOFF = 0.25

# Official IMDb non-commercial dataset source, used ONLY to prepare the local
# source catalog when the old imdb.db is not available. The final imdb.db is
# generated by the web crawler, not directly from these TSV files.
DATASET_URLS = {
    "title.basics": "https://datasets.imdbws.com/title.basics.tsv.gz",
    "title.ratings": "https://datasets.imdbws.com/title.ratings.tsv.gz",
}
DOWNLOAD_CHUNK_SIZE = 1024 * 1024
IMPORT_BATCH_SIZE = 5000
